# Generated by Django 6.1.1 on 2026-09-13 17:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('wallet', 'СБП / Электронный кошелек'), ('cash', 'Оплата при получении')], default='card', max_length=20, verbose_name='Метод оплаты')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('SUCCESS', 'Успешно оплачено'), ('FAILED', 'Ошибка оплаты')], default='PENDING', max_length=20, verbose_name='Статус платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платежная транзакция',
                'verbose_name_plural': 'Платежные транзакции',
                'ordering': ('-created_at',),
            },
        ),
    ]
