# Generated by Django 6.1.1 on 2026-09-11 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона для связи при доставке заказов.', max_length=20, verbose_name='Номер телефона')),
                ('default_shipping_address', models.TextField(blank=True, help_text='Адрес доставки по умолчанию для подстановки в /checkout/.', verbose_name='Основной адрес доставки')),
                ('avatar', models.ImageField(blank=True, help_text='Изображение профиля покупателя.', null=True, upload_to='avatars/%Y/%m/', verbose_name='Аватар профиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения профиля')),
                ('user', models.OneToOneField(help_text='Учетная запись Django, к которой привязан профиль.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
