[pytest]
DJANGO_SETTINGS_MODULE = config.settings.ci
testpaths = products orders users reviews payments tests
python_files = tests.py test_*.py *_tests.py
addopts =
    --reuse-db
    -v
    --cov=.
    --cov-report=term-missing
    --cov-report=html
    --cov-config=.coveragerc
    --cov-fail-under=70
filterwarnings =
    ignore::DeprecationWarning

