# Generated by Django 6.1.1 on 2026-09-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_remove_review_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='', verbose_name='Текст отзыва'),
            preserve_default=False,
        ),
    ]
