# Generated by Django 6.1.1 on 2026-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковской картой онлайн'), ('wallet', 'Электронный кошелек / СБП'), ('cash', 'При получении')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки и контакты'),
        ),
    ]
